export const ENTITLEMENT_SOURCES = ['STORE', 'CARRIER', 'MARKETPLACE'] as const;
export const CANONICAL_ENTITLEMENT_SOURCES = [...ENTITLEMENT_SOURCES, 'NONE'] as const;

export const STORE_EVENT_TYPES = [
  'INITIAL_PURCHASE',
  'RENEWAL',
  'CANCELLATION',
  'BILLING_ISSUE',
  'EXPIRATION',
  'UN_CANCELLATION',
] as const;

export const ENTITLEMENT_REASONS = [
  ...STORE_EVENT_TYPES,
  'MARKETPLACE_GRANT',
  'MARKETPLACE_REVOKE',
  'CARRIER_ACTIVE',
  'CARRIER_INACTIVE',
  'NO_ENTITLEMENT',
] as const;

export const NOTIFICATION_TYPES = ['PREMIUM_EXPIRES_SOON'] as const;
export const PRODUCT_IDS = ['premium_monthly'] as const;

export const ONE_DAY_MS = 24 * 60 * 60 * 1000;
export const EXPIRING_SOON_WINDOW_MS = ONE_DAY_MS;

export const MARKETPLACE_REVOKE_MAX_USER_IDS = 10_000;
export const MARKETPLACE_REVOKE_CHUNK_SIZE = 50;

export const CARRIER_POLL_BATCH_SIZE = 50;
export const CARRIER_POLL_CONCURRENCY = 10;
export const CARRIER_POLL_INTERVAL_MS = 5 * 60 * 1000;
export const CARRIER_POLL_LEASE_MS = 10 * 60 * 1000;

export const EXPIRY_RECONCILER_BATCH_SIZE = 100;
export const NOTIFICATION_SCHEDULER_BATCH_SIZE = 100;
export const NOTIFICATION_WORKER_BATCH_SIZE = 100;

export const MIN_JS_DATE_MS = -8_640_000_000_000_000;
export const MAX_JS_DATE_MS = 8_640_000_000_000_000;
